import { useEffect, useState } from 'react';
import core from 'virtual:twow-core';
import { classLoaders, guideLoaders, loadInstances, loadMatrix } from 'virtual:twow-loaders';
import type { ClassEntry, CoreData, GeneralGuideData, InstancesData, MatrixData } from '../types';

/**
 * Data loading. `src/data/*.json` is generated by `scripts/build-data.py`; the
 * `twow-data` Vite plugin (scripts/data-plugin.mjs) serves it split in two:
 *
 * - `core`: per-class summaries (the guide's viability table, recommendations,
 *   spec list and section headings), the instance index, glossary and meta.
 *   Bundled with the app, so home, search and every header render at once.
 * - one chunk per class, one per general guide (guide/*.md: professions, PvP,
 *   client setup, server mechanics), one for the dungeon and raid pages, one
 *   for the forum-era matrix archive: fetched when a page first needs them and
 *   cached.
 *
 * The plugin falls back to `src/data/fixtures/` when the generated files are
 * missing (or `VITE_USE_FIXTURES=1`); `core.isFixture` is then true.
 */
export const coreData: CoreData = core;

if (core.isFixture && import.meta.env.PROD) {
  console.warn('[data] src/data/*.json is missing; the site is showing development fixtures. Run scripts/build-data.py.');
}

const classCache = new Map<string, ClassEntry>();
const pending = new Map<string, Promise<ClassEntry | null>>();
const listeners = new Set<() => void>();
let instancesCache: InstancesData | null = null;
let matrixCache: MatrixData | null = null;
const guideCache = new Map<string, GeneralGuideData>();
const guidePending = new Map<string, Promise<GeneralGuideData | null>>();

function notify() {
  listeners.forEach((l) => l());
}

export function cachedClass(slug: string): ClassEntry | undefined {
  return classCache.get(slug);
}

export function loadClass(slug: string): Promise<ClassEntry | null> {
  const hit = classCache.get(slug);
  if (hit) return Promise.resolve(hit);
  const loader = classLoaders[slug];
  if (!loader) return Promise.resolve(null);
  let p = pending.get(slug);
  if (!p) {
    p = loader().then((m) => {
      classCache.set(slug, m.default);
      notify();
      return m.default;
    });
    pending.set(slug, p);
  }
  return p;
}

export function cachedInstances(): InstancesData | null {
  return instancesCache;
}

export async function loadInstancesData(): Promise<InstancesData | null> {
  if (instancesCache || !loadInstances) return instancesCache;
  instancesCache = (await loadInstances()).default;
  notify();
  return instancesCache;
}

export function cachedMatrix(): MatrixData | null {
  return matrixCache;
}

export async function loadMatrixData(): Promise<MatrixData> {
  if (!matrixCache) {
    matrixCache = (await loadMatrix()).default;
    notify();
  }
  return matrixCache as MatrixData;
}

/** One general guide by its route slug (`professions`, `pvp`, `mechanics`, ...). */
export function loadGuide(slug: string): Promise<GeneralGuideData | null> {
  const hit = guideCache.get(slug);
  if (hit) return Promise.resolve(hit);
  const loader = guideLoaders[slug];
  if (!loader) return Promise.resolve(null);
  let p = guidePending.get(slug);
  if (!p) {
    p = loader().then((m) => {
      guideCache.set(slug, m.default);
      notify();
      return m.default;
    });
    guidePending.set(slug, p);
  }
  return p;
}

/** Everything, for the offline smoke test (server rendering has no effects). */
export async function preloadAll(): Promise<void> {
  await Promise.all([
    ...Object.keys(classLoaders).map(loadClass),
    loadInstancesData(),
    loadMatrixData(),
    ...Object.keys(guideLoaders).map(loadGuide),
  ]);
}

export function cachedGuide(slug: string): GeneralGuideData | undefined {
  return guideCache.get(slug);
}

/** Re-render when any lazily loaded module arrives. */
function useDataVersion(): number {
  const [version, setVersion] = useState(0);
  useEffect(() => {
    const l = () => setVersion((v) => v + 1);
    listeners.add(l);
    return () => {
      listeners.delete(l);
    };
  }, []);
  return version;
}

/** The full class entry: `undefined` while it loads, `null` for an unknown class. */
export function useClassEntry(slug: string): ClassEntry | null | undefined {
  useDataVersion();
  const hit = classCache.get(slug);
  const known = slug in classLoaders;
  useEffect(() => {
    if (known && !classCache.has(slug)) void loadClass(slug);
  }, [slug, known]);
  if (hit) return hit;
  return known ? undefined : null;
}

/** The dungeon and raid pages: `undefined` while loading, `null` when the data has none. */
export function useInstancesData(): InstancesData | null | undefined {
  useDataVersion();
  useEffect(() => {
    if (!instancesCache && loadInstances) void loadInstancesData();
  }, []);
  if (instancesCache) return instancesCache;
  return loadInstances ? undefined : null;
}

/** A general guide: `undefined` while loading, `null` when the data has no such page. */
export function useGuideData(slug: string): GeneralGuideData | null | undefined {
  useDataVersion();
  const hit = guideCache.get(slug);
  const known = slug in guideLoaders;
  useEffect(() => {
    if (known && !guideCache.has(slug)) void loadGuide(slug);
  }, [slug, known]);
  if (hit) return hit;
  return known ? undefined : null;
}

export function useMatrixData(): MatrixData | undefined {
  useDataVersion();
  useEffect(() => {
    if (!matrixCache) void loadMatrixData();
  }, []);
  return matrixCache ?? undefined;
}

/** Warm the chunk for a class the pointer is heading to. */
export function prefetchClass(slug: string): void {
  if (!classCache.has(slug)) void loadClass(slug).catch(() => {});
}
