import type { ClassEntry, GlossaryTerm, MatrixData, Meta, SiteData } from '../types';

/**
 * Data loading. `src/data/*.json` is generated by `scripts/build-data.py`
 * (owned by the data pipeline) and is what production ships. `import.meta.glob`
 * is used instead of a static import so the app still compiles before those
 * files have been generated; in that case it falls back to the development
 * fixtures in `src/data/fixtures/`.
 *
 * Set `VITE_USE_FIXTURES=1` to force the fixtures during development.
 */
const forceFixtures = import.meta.env.VITE_USE_FIXTURES === '1';

const realFiles = import.meta.glob('./*.json', { eager: true, import: 'default' }) as Record<string, unknown>;

// The fixtures are only bundled for `vite dev` (or an explicit VITE_USE_FIXTURES=1
// build): both flags are compile-time constants, so a normal production build
// tree-shakes the fixture JSON away entirely.
const fixtureFiles: Record<string, unknown> =
  import.meta.env.DEV || forceFixtures
    ? (import.meta.glob('./fixtures/*.json', { eager: true, import: 'default' }) as Record<string, unknown>)
    : {};

const REQUIRED = ['classes', 'matrix', 'glossary', 'meta'] as const;

function pick(files: Record<string, unknown>, dir: string): Record<string, unknown> | null {
  const out: Record<string, unknown> = {};
  for (const name of REQUIRED) {
    const value = files[`${dir}${name}.json`];
    if (value === undefined) return null;
    out[name] = value;
  }
  return out;
}

let bundle = forceFixtures ? null : pick(realFiles, './');
let isFixture = false;

if (!bundle) {
  bundle = pick(fixtureFiles, './fixtures/');
  isFixture = bundle !== null;
  if (bundle && !forceFixtures && import.meta.env.PROD) {
    // Visible in the console of a production build so a bad deploy is obvious.
    console.warn(
      '[data] src/data/*.json is missing; the site is showing development fixtures. Run scripts/build-data.py.',
    );
  }
}

if (!bundle) {
  throw new Error(
    'No site data found. Generate src/data/*.json with scripts/build-data.py, or keep src/data/fixtures/*.json in place.',
  );
}

export const siteData: SiteData = {
  classes: bundle.classes as ClassEntry[],
  matrix: bundle.matrix as MatrixData,
  glossary: bundle.glossary as GlossaryTerm[],
  meta: bundle.meta as Meta,
  isFixture,
};
