#!/usr/bin/env python3
"""Coverage report and spot-check for the crawl/extraction.

Writes synthesis/coverage-report.md:
  - per section: expected (forum index), discovered, fetched, failed (with reasons), extracted topics/posts
  - site pages, images, wiki
  - spot-check: N random topic pages, compare raw HTML post ids/authors/dates with structured posts
"""
import glob
import gzip
import json
import math
import os
import random
import re
from collections import Counter, defaultdict

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
IDX = {r["forum_id"]: r for r in json.load(open(os.path.join(ROOT, "recon", "forum-index.json")))}
PER_PAGE = 35


def manifest():
    rows = {}
    for line in open(os.path.join(ROOT, "scrape", "manifest.jsonl")):
        if line.strip():
            r = json.loads(line)
            rows[r["url"]] = r
    return rows


def main():
    random.seed(20260910)
    rows = manifest()
    by_sec = defaultdict(lambda: Counter())
    fails = defaultdict(list)
    topics_disc = defaultdict(set)
    for r in rows.values():
        by_sec[r["section"]][(r["kind"], r["status"])] += 1
        if r["status"] == "failed":
            fails[r["section"]].append((r["url"], r.get("http"), r.get("note")))
        if r["kind"] == "topic":
            topics_disc[r["section"]].add(r["t"])
    # extracted
    topics = [json.loads(l) for l in open(os.path.join(ROOT, "structured", "forum", "topics.jsonl"))]
    ext_topics = Counter("forum-%d" % t["listed_in_forum"] for t in topics)
    ext_posts = Counter()
    ext_staff = Counter()
    for f in glob.glob(os.path.join(ROOT, "structured", "forum", "posts", "*.jsonl")):
        for line in open(f):
            if line.strip():
                p = json.loads(line)
                ext_posts["forum-%d" % p["forum_id"]] += 1
                if p["authority"] == "staff":
                    ext_staff["forum-%d" % p["forum_id"]] += 1
    lines = ["# Coverage report", "", "Generated by `scrape/coverage.py` from `scrape/manifest.jsonl` and the extraction outputs. Fetch dates: 2026-09-10 (UTC).", ""]
    lines += ["## Forums", "", "| forum | name | topics (index) | topics discovered | listing pages | topic pages fetched | failed | extracted topics | extracted posts | staff posts |", "|---|---|---|---|---|---|---|---|---|---|"]
    tot = Counter()
    for sec in sorted(by_sec, key=lambda s: (not s.startswith("forum-"), int(s.split("-")[1]) if s.startswith("forum-") else 0)):
        if not sec.startswith("forum-"):
            continue
        f = int(sec.split("-")[1])
        c = by_sec[sec]
        lp = c[("list", "done")]
        tp = c[("topic", "done")]
        fl = sum(v for (k, s), v in c.items() if s == "failed")
        lines.append("| %d | %s | %d | %d | %d | %d | %d | %d | %d | %d |" % (f, IDX[f]["name"], IDX[f]["topics"], len(topics_disc[sec]), lp, tp, fl, ext_topics[sec], ext_posts.get("forum-%d" % f, 0), ext_staff.get("forum-%d" % f, 0)))
        tot["idx"] += IDX[f]["topics"]; tot["disc"] += len(topics_disc[sec]); tot["lp"] += lp; tot["tp"] += tp; tot["fl"] += fl; tot["et"] += ext_topics[sec]
    lines.append("| **total** | | %d | %d | %d | %d | %d | %d | %d | %d |" % (tot["idx"], tot["disc"], tot["lp"], tot["tp"], tot["fl"], tot["et"], sum(ext_posts.values()), sum(ext_staff.values())))
    lines += ["", "Notes: topics discovered can differ slightly from the index count because global announcements are listed in every forum (deduplicated to the forum where first seen) and a few topics were deleted between the index snapshot and the listing crawl. Extracted posts are attributed to the topic's true forum (breadcrumb), so announcement posts listed under Patch Notes count under Announcements.", ""]
    excluded = [55, 57, 66, 68]
    lines += ["Not crawled by decision: " + ", ".join("f=%d %s (%d topics)" % (f, IDX[f]["name"], IDX[f]["topics"]) for f in excluded), ""]
    c = by_sec["site"]
    lines += ["## Main site", "", "Pages fetched: %d, failed: %d." % (c[("site", "done")], c[("site", "failed")]), ""]
    for u, h, n in fails["site"]:
        lines.append("- %s: %s" % (u, n or h))
    c = by_sec["images"]
    lines += ["", "## Images", "", "%d image URLs referenced from patch-note posts on turtlecraft.gg/images were queued; all %d returned HTTP 404 on 2026-09-10 (the images directory is already gone). None archived." % (sum(c.values()), c[("image", "failed")]), ""]
    # wiki
    wp = os.path.join(ROOT, "structured", "wiki", "pages.jsonl")
    if os.path.exists(wp):
        pages = [json.loads(l) for l in open(wp)]
        ns = Counter(p["ns"] for p in pages)
        lines += ["## Wiki (turtle-wow.fandom.com, via MediaWiki API)", "", "Pages archived: %d (articles %d, categories %d, templates %d, project %d); Turtle-content pages: %d; with infobox: %d." % (len(pages), ns.get(0, 0), ns.get(14, 0), ns.get(10, 0), ns.get(4, 0), sum(1 for p in pages if p["is_turtle_content"]), sum(1 for p in pages if p["infobox"])), ""]
    # failures list
    lines += ["## Failed forum pages", ""]
    for sec in sorted(fails):
        if sec in ("site", "images"):
            continue
        for u, h, n in fails[sec]:
            lines.append("- %s: HTTP %s %s" % (u, h, n or ""))
    # spot check
    lines += ["", "## Spot-check: extracted posts vs raw HTML", ""]
    topic_pages = [r for r in rows.values() if r["kind"] == "topic" and r["status"] == "done"]
    sample = random.sample(topic_pages, 40)
    posts_by_id = {}
    for f in glob.glob(os.path.join(ROOT, "structured", "forum", "posts", "*.jsonl")):
        for line in open(f):
            if line.strip():
                p = json.loads(line)
                posts_by_id[p["post_id"]] = p
    ok = mism = 0
    details = []
    for r in sample:
        html = gzip.open(os.path.join(ROOT, r["path"])).read().decode("utf-8", "replace")
        raw_ids = [int(x) for x in re.findall(r'<div id="p(\d+)" class="post', html)]
        raw_authors = re.findall(r'<p class="author">.*?class="username(?:-coloured)?"[^>]*>([^<]+)</a>.*?&raquo;\s*</span>([^<]+)', html, re.S)
        missing = [i for i in raw_ids if i not in posts_by_id]
        bad = []
        for (a, d), pid in zip(raw_authors, raw_ids):
            p = posts_by_id.get(pid)
            if p and (p["author"] != a.strip() or (p.get("date_raw") or "").strip() != d.strip()):
                bad.append((pid, a.strip(), d.strip(), p["author"], p.get("date_raw")))
        if missing or bad:
            mism += 1
            details.append("- %s: %d posts in raw, missing %s, mismatches %s" % (r["url"], len(raw_ids), missing[:5], bad[:3]))
        else:
            ok += 1
            details.append("- %s: %d posts, all ids/authors/dates match" % (r["url"], len(raw_ids)))
    lines += ["Sampled %d random topic pages: %d fully consistent, %d with discrepancies." % (len(sample), ok, mism), ""] + details
    out = os.path.join(ROOT, "synthesis", "coverage-report.md")
    with open(out, "w") as fh:
        fh.write("\n".join(lines) + "\n")
    print("\n".join(lines[:60]))
    print("... spot-check: %d ok, %d mismatched" % (ok, mism))


if __name__ == "__main__":
    main()
